name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  Android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Setup Env
        uses: ./.github/actions/setup

      - name: Build Packages
        shell: bash
        run: |
          cd android
          chmod +x gradlew
          echo "${{ secrets.KEYSTORE_STORE_FILE_BASE64 }}" | base64 --decode > app/${{ secrets.KEYSTORE_STORE_FILE }}
          ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.KEYSTORE_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.KEYSTORE_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_KEY_PASSWORD }}'
          rm -f app/${{ secrets.KEYSTORE_STORE_FILE }}

      # Push tag to GitHub if package.json version's tag is not tagged
      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Create git tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          version: ${{ env.PACKAGE_VERSION }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"

      - name: Generate file MD5
        run: |
          cd android/app/build/outputs/apk/release
          md5sum *.apk

      - name: Upload Artifact
        uses: ./.github/actions/upload-artifact
        env:
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

  # Android_SL:
  #   name: Android_SL
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out git repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: statusbar_lyric

  #     - name: Setup Env
  #       uses: ./.github/actions/setup

  #     - name: Build Packages
  #       shell: bash
  #       run: |
  #         cd android
  #         echo ${{ secrets.KEYSTORE_STORE_FILE_BASE64 }} | base64 --decode > app/${{ secrets.KEYSTORE_STORE_FILE }}
  #         ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.KEYSTORE_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.KEYSTORE_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_KEY_PASSWORD }}'
  #         rm -f app/${{ secrets.KEYSTORE_STORE_FILE }}

  #     # Push tag to GitHub if package.json version's tag is not tagged
  #     - name: Get package version
  #       run: |
  #         node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
  #         echo "COMMIT_SHA=$(git show -s --format=%H)" >> $GITHUB_ENV

  #     - name: Create git tag
  #       uses: pkgdeps/git-tag-action@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         github_repo: ${{ github.repository }}
  #         version: ${{ env.PACKAGE_VERSION }}
  #         git_commit_sha: ${{ env.COMMIT_SHA }}
  #         git_tag_prefix: "v"

  #     - name: Generate file MD5
  #       run: |
  #         echo "current commit sha: ${{ env.COMMIT_SHA }}"
  #         cd android/app/build/outputs/apk/release
  #         md5sum *.apk

  #     - name: Upload Artifact
  #       uses: ./.github/actions/upload-artifact
  #       env:
  #         PACKAGE_TYPE: 'Android_SL'
  #         PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

  # Android_5:
  #   name: Android_5
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Check out git repository
  #       uses: actions/checkout@v4
  #       with:
  #         ref: android_5

  #     - name: Setup Env
  #       uses: ./.github/actions/setup

  #     - name: Build Packages
  #       shell: bash
  #       run: |
  #         cd android
  #         echo ${{ secrets.KEYSTORE_STORE_FILE_BASE64 }} | base64 --decode > app/${{ secrets.KEYSTORE_STORE_FILE }}
  #         ./gradlew assembleRelease -PMYAPP_UPLOAD_STORE_FILE='${{ secrets.KEYSTORE_STORE_FILE }}' -PMYAPP_UPLOAD_KEY_ALIAS='${{ secrets.KEYSTORE_KEY_ALIAS }}' -PMYAPP_UPLOAD_STORE_PASSWORD='${{ secrets.KEYSTORE_PASSWORD }}' -PMYAPP_UPLOAD_KEY_PASSWORD='${{ secrets.KEYSTORE_KEY_PASSWORD }}'
  #         rm -f app/${{ secrets.KEYSTORE_STORE_FILE }}

  #     # Push tag to GitHub if package.json version's tag is not tagged
  #     - name: Get package version
  #       run: |
  #         node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
  #         echo "COMMIT_SHA=$(git show -s --format=%H)" >> $GITHUB_ENV

  #     - name: Create git tag
  #       uses: pkgdeps/git-tag-action@v3
  #       with:
  #         github_token: ${{ secrets.GITHUB_TOKEN }}
  #         github_repo: ${{ github.repository }}
  #         version: ${{ env.PACKAGE_VERSION }}
  #         git_commit_sha: ${{ env.COMMIT_SHA }}
  #         git_tag_prefix: "v"

  #     - name: Generate file MD5
  #       run: |
  #         echo "current commit sha: ${{ env.COMMIT_SHA }}"
  #         cd android/app/build/outputs/apk/release
  #         md5sum *.apk

  #     - name: Upload Artifact
  #       uses: ./.github/actions/upload-artifact
  #       env:
  #         PACKAGE_TYPE: 'Android_5'
  #         PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}

  Release:
    name: Release
    runs-on: ubuntu-latest
    needs: [Android]
    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Get package version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
          merge-multiple: true

      - name: Extract changelog for current version
        run: |
          VERSION="${{ env.PACKAGE_VERSION }}"
          
          # 从 CHANGELOG.md 提取当前版本的内容
          awk -v ver="$VERSION" '
            /^## \['"$VERSION"'\]/ { found=1; next }
            found && /^## \[/ { exit }
            found { print }
          ' CHANGELOG.md > release_notes.md
          
          # 添加 MD5 校验和
          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "" >> release_notes.md
          echo "## 文件校验" >> release_notes.md
          echo "" >> release_notes.md
          echo "### MD5 校验和" >> release_notes.md
          echo "" >> release_notes.md
          echo '```' >> release_notes.md
          cd artifacts
          md5sum *.apk >> ../release_notes.md
          cd ..
          echo '```' >> release_notes.md
          
          # 添加安装说明
          echo "" >> release_notes.md
          echo "---" >> release_notes.md
          echo "" >> release_notes.md
          echo "## 安装说明" >> release_notes.md
          echo "" >> release_notes.md
          echo "### 推荐下载" >> release_notes.md
          echo "" >> release_notes.md
          echo "- **大多数用户**: 下载 \`universal.apk\` (通用版，兼容所有设备)" >> release_notes.md
          echo "- **追求体积小**: 根据手机架构选择对应的 APK" >> release_notes.md
          echo "  - \`arm64-v8a.apk\`: 64位 ARM 处理器 (大多数现代手机)" >> release_notes.md
          echo "  - \`armeabi-v7a.apk\`: 32位 ARM 处理器 (较老的手机)" >> release_notes.md
          echo "  - \`x86_64.apk\`: 64位 x86 处理器 (模拟器)" >> release_notes.md
          echo "  - \`x86.apk\`: 32位 x86 处理器 (老模拟器)" >> release_notes.md

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./release_notes.md
          prerelease: false
          draft: false
          tag_name: v${{ env.PACKAGE_VERSION }}
          files: |
            artifacts/one-music-mobile-v${{ env.PACKAGE_VERSION }}-arm64-v8a.apk
            artifacts/one-music-mobile-v${{ env.PACKAGE_VERSION }}-armeabi-v7a.apk
            artifacts/one-music-mobile-v${{ env.PACKAGE_VERSION }}-x86_64.apk
            artifacts/one-music-mobile-v${{ env.PACKAGE_VERSION }}-x86.apk
            artifacts/one-music-mobile-v${{ env.PACKAGE_VERSION }}-universal.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
